In [2]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(100000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 23.9 ms, sys: 43.4 ms, total: 67.3 ms
Wall time: 126 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 78.9 ms, sys: 37.1 ms, total: 116 ms
Wall time: 136 ms


# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 0.93954731,  0.83309559,  1.31668883],
       [ 0.22571602, -0.62135957,  0.62759372]])

In [9]:
data * 10

array([[ 9.39547312,  8.3309559 , 13.16688831],
       [ 2.25716023, -6.21359565,  6.27593725]])

In [10]:
data + data

array([[ 1.87909462,  1.66619118,  2.63337766],
       [ 0.45143205, -1.24271913,  1.25518745]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype 

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[-0.00000000e+000, -0.00000000e+000],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  1.61590357e+184]],

       [[ 5.28207420e-091,  8.61128850e-043],
        [ 2.36747059e+179,  1.40415334e+165],
        [ 3.99910963e+252,  8.34402697e-309]]])